/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#213145",
        "steel-border": "#E2E8F0",
        "outline": "#76777d",
        "canvas-clean": "#F8FAFC",
        "primary-fixed-dim": "#bec6e0",
        "amber-highlight": "#F59E0B",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#131b2e",
        "tertiary-container": "#00164e",
        "on-background": "#0b1c30",
        "surface-container-highest": "#d3e4fe",
        "secondary": "#904d00",
        "on-tertiary-fixed-variant": "#264191",
        "inverse-primary": "#bec6e0",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "on-surface": "#0b1c30",
        "slate-card-dark": "#112240",
        "tertiary-fixed": "#dce1ff",
        "on-secondary-fixed-variant": "#6e3900",
        "on-secondary-fixed": "#2f1500",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#00164e",
        "background": "#f8f9ff",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#e5eeff",
        "on-surface-variant": "#45464d",
        "secondary-fixed-dim": "#ffb77d",
        "primary-container": "#0D2346",
        "surface": "#f8f9ff",
        "on-secondary-container": "#663500",
        "surface-container-high": "#dce9ff",
        "on-tertiary-container": "#6780d3",
        "surface-bright": "#f8f9ff",
        "on-primary-fixed-variant": "#3f465c",
        "surface-variant": "#d3e4fe",
        "surface-container-low": "#eff4ff",
        "on-primary-container": "#7c839b",
        "surface-dim": "#cbdbf5",
        "primary": "#0B1C30",
        "on-primary": "#ffffff",
        "outline-variant": "#c6c6cd",
        "tertiary": "#0D2346",
        "secondary-container": "#fe932c",
        "surface-tint": "#565e74",
        "on-secondary": "#ffffff",
        "primary-fixed": "#dae2fd",
        "secondary-fixed": "#ffdcc3",
        "tertiary-fixed-dim": "#b6c4ff",
        "slate-surface-dark": "#0B1C30",
        "navy-deep": "#071322",
      },
      borderRadius: {
        "none": "0px",
        "sm": "0.375rem",
        "DEFAULT": "0.625rem",
        "md": "0.5rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
      spacing: {
        "section-stack-lg": "9rem",
        "section-stack-sm": "3rem",
        "gutter-md": "1.5rem",
        "gutter-sm": "1rem",
        "margin-mobile": "1.25rem",
        "margin-desktop": "4rem",
        "gutter-lg": "2rem",
        "section-stack-md": "6rem",
      },
      fontFamily: {
        "sans": ["Manrope", "sans-serif"],
        "display-hero-mobile": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "metric-stat": ["Space Grotesk", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "display-hero": ["Montserrat", "sans-serif"],
        "label-caps": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "body-sm": ["Manrope", "sans-serif"],
        "headline-sm": ["Montserrat", "sans-serif"],
        "spec-code": ["Space Grotesk", "monospace"],
        "body-lg": ["Manrope", "sans-serif"],
      },
      fontSize: {
        "display-hero-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["38px", { lineHeight: "46px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "metric-stat": ["52px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "display-hero": ["64px", { lineHeight: "72px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "0em", fontWeight: "600" }],
        "spec-code": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
